title: 我的书签
template: bookmarks2

categories:
  - name: 接码
    icon: fas fa-folder
    sites:
      - name: 天启
        url: https://web.tqsms.xyz/#/message/getCode
        icon: fas fa-link
        description: "天启"
      - name: 豪猪
        url: https://h5.haozhuma.cn/index.php
        icon: fas fa-link
        description: "豪猪"
      - name: 椰子
        url: http://yezi779.com:90/
        icon: fas fa-link
        description: "椰子"
      - name: 谷歌临时邮箱
        url: https://22.do
        icon: fas fa-link
        description: "谷歌临时邮箱"

  - name: 好玩的东东
    icon: fas fa-folder
    sites:
      - name: 朋友圈点赞生成器
        url: https://akarin.dev/WechatMomentScreenshot/
        icon: fas fa-link
        description: "好玩的东东"
      - name: 粤语翻译
        url: https://yue.micblo.com
        icon: fas fa-link
        description: "粤语翻译"
      - name: 在线正则匹配
        url: https://regex-vis.com
        icon: fas fa-link
        description: "在线正则匹配"
