title: "我的小网站"          # 页面标题
subtitle: "搭建"  # 页面副标题
categories:                   # 该页面的分类和网站
  - name: "web"
    icon: "fas fa-code"
    sites:
      - name: "api-check"
        url: "https://api-check-inky.vercel.app"
        icon: "fab fa-v"
        description: "check-api"
      - name: "SubStore"
        url: "https://dyeixmidoovq.us-east-1.clawcloudrun.com/subs"
        icon: "fab fa-link"
        description: "SubStore"
      - name: "主页 | 视频站"
        url: "https://alist.221041.xyz"
        icon: "fas fa-link"
        description: "视频站"
      - name: "email"
        url: "https://email.221041.xyz/"
        icon: "fas fa-link"
        description: "基于cloudfare的临时邮箱网站"
      - name: "webssh"
        url: "https://webssh.bactdt.workers.dev/"
        icon: "fas fa-link"
        description: "webssh"
      - name: "cock"
        url: "https://cockli.serv00.net/"
        icon: "fas fa-link"
        description: "cockli"      
      
      # 更多网站...
