title: "我的小网站"          # 页面标题
subtitle: "搭建"  # 页面副标题
categories:                   # 该页面的分类和网站
  - name: "web"
    icon: "fas fa-code"
    sites:
      - name: "deeplx"
        url: "https://deeplx-wine.vercel.app"
        icon: "fab fa-v"
        description: "deeplx"
      - name: "cdhost"
        url: "https://cdhost.vercel.app"
        icon: "fab fa-v"
        description: "Cdhost"
      - name: "SubStore"
        url: "https://dyeixmidoovq.us-east-1.clawcloudrun.com/subs"
        icon: "fab fa-link"
        description: "SubStore"
      - name: "主页 | 视频站"
        url: "https://alist.221041.xyz"
        icon: "fas fa-link"
        description: "视频站"
      - name: "email"
        url: "https://email.221041.xyz/"
        icon: "fas fa-link"
        description: "基于cloudfare的临时邮箱网站"
      
      # 更多网站...
