- name: 首页
  icon: fas fa-home
  id: home
  active: true
- name: 书签
  icon: fas fa-bookmark
  id: bookmarks 
- name: 书签2
  icon: fas fa-bookmark
  id: bookmarks2
- name: 小网站
  icon: fas fa-bookmark
  id: web
